server:
  port: 8770

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"
