server:
  port: 8780

spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "hystrix.stream"

turbine:
  app-config: service-hi,service-lucy
  aggregator:
    cluster-config: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream